#!/bin/bash
# Copyright (c) 2016, Jeffrey Maggio and Joseph Bartelmo
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
# associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all copies or substantial 
# portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
# LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

#i messed up fdisk somehow :shrug:
mount -t ext4 /dev/sda1 /phobos

#Adjust as needed
pins=(57 160 161 162 163 164 165 166)
cores=(0 1 2 3)
serverDir="/phobos/goddard/server"

#blows open permissions for all else
chmod 777 -R "/sys/class/gpio"

#sets up, and blows open permissions for each pin
for index in "${pins[@]}"; do
    echo "$index" > "/sys/class/gpio/export"
    chmod 777 "/sys/class/gpio/gpio$index/value"
    chmod 777 "/sys/class/gpio/gpio$index/direction"
    echo "out" > "/sys/class/gpio/gpio$index/direction"
    echo "0" > "/sys/class/gpio/gpio$index/value"
done

#Enable all cores
echo "0" > "/sys/devices/system/cpu/cpuquiet/tegra_cpuquiet/enable"
echo "performance" > "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"

for index in "${cores[@]}"; do
    echo "1" > "/sys/devices/system/cpu/cpu$index/online"
done

cd $serverDir; nohup python server.py >$serverDir/serverlog.txt &
exit 0

