'''
ark9719
6/17/2016
'''
import logging
import sys
import time
import os.path
import json
from collections import namedtuple
from System import System

#Assumes that the server handeled validation
def parseConfig(json_string):
    config = json.loads(json_string, object_hook=lambda configObject: namedtuple('X', configObject.keys())(*configObject.values()));
    return config

def initOutput(config):
    """
    Create the output/timestamp directory for the files generated by this run (log/telemetry)
    :param config:
    :return:
    """
    t = time.localtime()
    timestamp = time.strftime('%b-%d-%Y_%H%M%S', t)

    if not os.path.exists(config.logging.outputPath + '/output/' + timestamp + '/'):
        os.makedirs(config.logging.outputPath + '/output/' + timestamp + '/')

    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    # create debug file handler and set level to debug
    handler = logging.FileHandler(os.path.join(config.logging.outputPath + '/output/' + timestamp + '/', "log.txt"),"w")
    handler.setLevel(logging.INFO)
    formatter = logging.Formatter("%(levelname)s - %(message)s")
    handler.setFormatter(formatter)
    logger.addHandler(handler)

    if (os.path.isfile('output/' + timestamp + '/' + config.logging.logName + '_machine_log.csv')):
        print("The output file you specified in the configuration file already exists.\n")
        print("The statistics from the previous reads will be overwritten if you don't specify a new file.")
        print("Do you wish to continue?")
        answer = raw_input("Y / N: ")
        if answer.lower() in ('n', 'no'):
            print ("The program will terminate ")
            sys.exit()

    return timestamp


def run(json_string):
    print("Starting...")

    print("Loading configurations...")
    logging.info('Reading in settings configurations')
    config = parseConfig(json_string)

    logging.info("Preparing output directories")
    timestamp = initOutput(config)

    System(config, timestamp)




def main():
    if len(sys.argv) < 2:
        print('To few arguments, please specify a json string with which to load configuration')
        print('\tUsage: run.py json_string')
        return;
    print ('\ntest\n\n')
    print(sys.argv);
    sys.argv.pop(0);
    json_string = ''.join(sys.argv)
    print('\n\n\n' + json_string)
    run(json_string)

main()

